### ISSUE TITLE
IronPython support

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.interface#10]
In https://bugs.launchpad.net/zope.interface/+bug/388433, @sanxiyn reports:

> See: http://mail.zope.org/pipermail/interface-dev/2009-June/000232.html
> 
> When setting **implemented** of a type, if it is a built-in type an exception is raised. zope.interface should catch AttributeError as well as TypeError.

I followed up:

> I would be glad to patch the 'implementedByFallback' function (the one you reference, I believe), but need to be able to test it under CPython. I plan to pass a class whose '**setattr**' raises an AttributeError, but am not certain how to get the rest of its state set to get to the point where it breaks for you.
> 
> Can you please provide a traceback or a code sample which triggers the bug for you?

**Comment by jamadden** [comment]
Closing this because, as with Jython, there is no CFFI support on IronPython (AFAICS).

**Comment by icemac** [comment]
I am closing this old issue. Feel free to re-open it if there are any news about the topic.
