### ISSUE TITLE
Fix process of reference count during GC

### ISSUE THREAD

**Issue by y-fujisaki2** [zopefoundation/zope.interface#100]
When we subtract reference counter of an object, the destructor is automatically called if the value of counter is 0. 
At the same time an error occurs, as the GC executed while the destructor is still in running phase.
To eliminate the error, we have added below program which exclude objects from GC in the destructor in line 4.

static void
Wrapper_dealloc(Wrapper *self)
{
  PyObject_GC_UnTrack((PyObject *)self); //Add this line to eliminate self from GC
  Wrapper_clear(self);
  self->ob_type->tp_free((PyObject*)self);
}

Patch: [zope.interface.zip](https://github.com/zopefoundation/zope.interface/files/1291364/zope.interface.zip)

**Comment by mgedmin** [comment]
Could you please re-submit this as a GitHub pull request?

**Comment by y-fujisaki2** [comment]
Thank you so much for your advice. I done it.

**Comment by y-fujisaki2** [comment]
Thank you so much for merging this fix.
