### ISSUE TITLE
Problems with installing zope.interface on Amazon Linux

### ISSUE THREAD

**Issue by TheNavigat** [zopefoundation/zope.interface#107]
Hello there!

Amazon Linux is causing us problems with Certbot. I have done some investigation, and it turns out that for some reason installing `zope.interface` on Amazon Linux with the global variable `PYTHON_INSTALL_LAYOUT` set to `amzn` doesn't work.

Here are links for comments that show detailed investigation:

https://github.com/certbot/certbot/issues/2823#issuecomment-344063028
https://github.com/certbot/certbot/issues/2823#issuecomment-344071061
https://github.com/certbot/certbot/issues/2823#issuecomment-344904619
https://github.com/certbot/certbot/issues/2823#issuecomment-344907996

Can you please take a look?

**Comment by jamadden** [comment]
The original issue has been closed, so I'm going to close this one too. Feel free to (re)open if this is still a reproducible problem.
