### ISSUE TITLE
Sync namespace packages approach

### ISSUE THREAD

**Issue by frenzymadness** [zopefoundation/zope.interface#114]
Hello.

As mentioned in Python docs [0]:
> **Every** distribution that uses the namespace package must include an identical `__init__.py`. If any distribution does not, it will cause the namespace logic to fail and the other sub-packages will not be importable. Any additional code in `__init__.py` will be inaccessible.

but it seems that zope.deprecation [1] and zope.configuration [2] have different content in namespace `__init__.py` files than zope.interface.

It would be nice to sync namespace `__init__.py` files across modules maintained by Zope foundation so they will be installable in parallel.

[0] https://packaging.python.org/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages
[1] https://github.com/zopefoundation/zope.deprecation/blob/master/src/zope/__init__.py
[2] https://github.com/zopefoundation/zope.configuration/blob/master/src/zope/__init__.py

Possibly related to:
* https://github.com/zopefoundation/zope.interface/issues/107
* https://github.com/zopefoundation/zope.interface/issues/68
* https://github.com/zopefoundation/zope.interface/issues/97

**Comment by jamadden** [comment]
I would add that, while byte-for-byte identical files might be nice, the differences here are minor and shouldn't be of any concern. All the referenced packages depend on setuptools in `install_requires`, so no matter which file gets executed, the net effect will be to register `zope` as a namespace package with `pkg_resources`. (The `else` clause in the file in this package will never be executed.)

**Comment by icemac** [comment]
@jamadden
So you'd suggest to close this issue as its suggested solution probably will not resolve the issue?
Do you think it is still necessary to keep the try-except block here in `zope.interface`? (`setuptools` is actually an install dependency.)

**Comment by jamadden** [comment]
@icemac #115 😄

**Comment by frenzymadness** [comment]
Thank you for taking a look. I'll see if it solves out troubles with namespace packages when you'll release a new version and we'll do an update.

**Comment by icemac** [comment]
@frenzymadness I released the fix for this issue in version 4.5.0, see https://pypi.org/project/zope.interface/4.5.0/. Does it help with the problem you are trying to solve?
