### ISSUE TITLE
Ease Python 3 porting

### ISSUE THREAD

**Issue by ale-rt** [zopefoundation/zope.interface#117]
There are quite some packages in Plone that are broken because of these and similar lines:
https://github.com/zopefoundation/zope.interface/blob/c1b436de3f36bb533634b3287a601cd81b63ccb2/src/zope/interface/adapter.py#L327-L328
In many cases the quick fix is just to redefine `name=str(name)`.

To ease the porting process I would modify them to something like:

```
if not isinstance(name, STRING_TYPES):
     try:
          name = str(name)
          log.warning('name is not a string which is a deprecated behavior')
    except:
          raise ValueError('name should be a string') 
```

**Comment by jamadden** [comment]
Interestingly, that check was added specifically *because* of issues in Plone. See #75 for the original conversation.

**Comment by ale-rt** [comment]
LOL @jamadden :)
I think I will use that kind of patch locally to identify the fixes I have to make. Thanks for having a look!
