### ISSUE TITLE
Documentation on implements is out of date

### ISSUE THREAD

**Issue by bowbahdoe** [zopefoundation/zope.interface#119]
The current documentation still shows `zope.interface.implements` as the method for declaring that a class implements an interface. Best I can tell, this will always throw an error in python 3.6

**Comment by jugmac00** [comment]
I worked on updating the Zope Developer Documentation (incl. interface/component article) during the Saltalbs sprint (Oct 2018). After the merge, it will be available at
https://github.com/zopefoundation/Zope/blob/master/docs/zdgbook/ComponentsAndInterfaces.rst

**Comment by bowbahdoe** [comment]
Out of curiosity what branch are you working on?

**Comment by jugmac00** [comment]
Sorry, I thought it would be a quick merge.

Here is the pull request
https://github.com/zopefoundation/Zope/pull/359

and the updated (but not final documentation):
https://github.com/zopefoundation/Zope/blob/update-components-documentation/docs/zdgbook/ComponentsAndInterfaces.rst
