### ISSUE TITLE
names() implementation contradicts documentation in Python 3

### ISSUE THREAD

**Issue by vernans** [zopefoundation/zope.interface#134]
There's something I noticed while porting some code to Python 3. The implementation of names() in InterfaceClass doesn't return a sequence, as the documentation states, but a dict view.
To me this seems weird – have a function return two different types that don't represent the same way/idea of working with the data underneath it. 
How do we proceed with this?
I'd prefer to return a list, even if we don't take advantage of the new dict behaviour, because this would be a breaking change in the API.

https://github.com/zopefoundation/zope.interface/blob/3042b9fa7c37aa0d0b61efcdb0b1a436fef9bf59/src/zope/interface/interface.py#L389-L399

**Comment by tseaver** [comment]
The term "sequence" implies that the thing can be iterated, not that it is a list, and `Interface.names` behaves exactly as specified:

```python
$ python3.6
Python 3.6.7 (default, Oct 22 2018, 11:30:50) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from zope.interface import Interface
>>> class IFoo(Interface):
...     def bar():
...         """Bar"""
... 
>>> IFoo.names()
dict_keys(['bar'])
>>> for name in IFoo.names():
...     print(name)
... 
bar
```

Code that straddles Python2 / Python3, including clients of `zope.interface`, needs to be careful *not* to assume that such functions actually return lists:

```bash
$ python2.7.

**Comment by jamadden** [comment]
However, `dict.keys()` and `dict.items()` aren't *technically* `Sequence` objects:
```pycon
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06)
>>> from collections.abc import Sequence
>>> d = dict()
>>> isinstance(d.items(), Sequence)
False
>>> isinstance(d.keys(), Sequence)
False
```

A `Sequence` is a `Collection` and `Reversible`; dict views are `Collections`, but they're not `Reversible`.

**Comment by jamadden** [comment]
> A "sequence" typically can also be "indexed" 

Is indexing this return value useful? They come from a dictionary, which prior to 3.7 has no order guarantees. 

Perhaps [the docs](https://zopeinterface.readthedocs.io/en/latest/api/specifications.html?highlight=names#zope.interface.interfaces.IInterface.names) just need to be updated to refer to a 'collection' instead of a 'sequence' to set expectation appropriately.
