### ISSUE TITLE
Fix setup.py when using plain distutils

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.interface#14]
In https://bugs.launchpad.net/zope.interface/+bug/629086, @zseil reported:

> Support for installing zope.interface with plain distutils has deteriorated a bit over the recent releases. There are currently two problems with the setup script - the list of packages is incomplete (reported as bug #611362) and the coptimization extension never gets built when not using setuptools. The attached patch fixes both problems for me. It also removes Python 2.3 support from the setup script, since zope.interface itself doesn't support that version anymore.
>
> (Tested on Windows, Python 2.5 with a C compiler and Python 2.6 without a C compiler, in both cases without setuptools installed)

with patch:  https://bugs.launchpad.net/zope.interface/+bug/629086/+attachment/1537986/+files/distutils-compatibility.patch

**Comment by mgedmin** [comment]
Huh, from the patch mentioned in #13:

```diff
@@ -121,7 +122,13 @@
         "Topic :: Software Development :: Libraries :: Python Modules",
       ],
 
-      packages = ['zope', 'zope.interface', 'zope.interface.tests'],
+      packages = [
+        'zope',
+        'zope.interface',
+        'zope.interface.tests',
+        'zope.interface.common',
+        'zope.interface.common.tests',
+      ],
       package_dir = {'': 'src'},
       cmdclass = {'build_ext': optional_build_ext,
                   },
```

I see no reason to explicitly enumerate *half* of zope.interface subpackages in the setup.py.  Let's either apply that or use `setuptools.find_packages()`.

**Comment by mgedmin** [comment]
Whoops, commented on the wrong bug.
