### ISSUE TITLE
Normal metaclass resolution not applied to InterfaceClass

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.interface#16]
In https://bugs.launchpad.net/zope.interface/+bug/791218, @lrowe reported:

> While experimenting with my InterfaceClass subclass I noticed that it was only being used when it was specified as the first of the bases. I believe this is because InterfaceClass is not a subclass of `type`, so the normal metaclass derivation logic is not applied. The branch at svn+ssh://svn.zope.org/repos/main/zope.interface/branches/elro-metaclass-resolution implements that logic in `InterfaceClass.__new__`, picking from the base metaclasses that metaclass which subclasses all other base metaclasses.
> 
> The motivating factor here is: I need an Interface with a hook that gets called after `InterfaceClass.__init__` to allow for:
> - Checking that field names supplied as tagged values from directives correspond to actual field names to detect typos.
> - Registering the `Interface` instance for further configuration to be executed by a zope.configuration action.
> 
> Relevant changeset: http://zope3.pov.lt/trac/changeset/121497/zope.interface/branches/elro-metaclass-resolution
> 
> Example InterfaceClass subclass: http://dev.plone.org/plone/browser/plone.supermodel/branches/elro-directives/plone/supermodel/model.py#L58

**Comment by lrowe** [comment]
For my defence I can only plead that stubbornness led me to strange places...

**Comment by tseaver** [comment]
I'm going to reverse myself and say that this behavior is not-a-bug.  @lrowe, if you can come up with a backward-compatible mechanism which solves your usecase, please submit a PR.

**Comment by pbauer** [comment]
@lrowe In Python 3 this seems to work as we found out while porting plone.supermodel:

 ```
>>> from zope.interface import Interface
>>> from zope.interface.interface import InterfaceClass
>>> class SpecialClass(InterfaceClass): pass
...
>>> Special = SpecialClass('Special')
>>> class I(Interface):
...     pass

>>> class S(Special):
...     pass

>>> class Combined(I, S):
...     pass

>>> isinstance(Combined, SpecialClass)
True
```
