### ISSUE TITLE
Possible problem with _ImmutableDeclaration?

### ISSUE THREAD

**Issue by jensens** [zopefoundation/zope.interface#162]
With the current master and Plone there are some failiures. One of them here:

```
Failed example:
    IKeyReference(item_c)
Expected:
    Traceback (most recent call last):
    ...
    TypeError: ('Could not adapt', <SimpleItem at c>,
    <InterfaceClass zope.keyreference.interfaces.IKeyReference>)
Got:
    Traceback (most recent call last):
      File "/home/jensens/.pyenv/versions/3.7.5/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest README.rst[112]>", line 1, in <module>
        IKeyReference(item_c)
      File "/home/jensens/.dotfiles/.buildout/shared-eggs/zope.component-4.5-py3.7.egg/zope/component/_api.py", line 141, in adapter_hook
        return sitemanager.queryAdapter(object, interface, name, default)
      File "/home/jensens/ws/cdev/p52/src/zope.interface/src/zope/interface/registry.py", line 348, in queryAdapter
        return self.adapters.queryAdapter(object, interface, name, default)
      File "/home/jensens/ws/cdev/p52/src/zope.interface/src/zope/interface/adapter.py", line 533, in _uncached_lookup
        self._subscribe(*required)
      File "/home/jensens/ws/cdev/p52/src/zope.interface/src/zope/interface/adapter.py", line 511, in _subscribe
        r.subscribe(self)
      File "/home/jensens/ws/cdev/p52/src/zope.interface/src/zope/interface/interface.py", line 235, in subscribe
        self._dependents[dependent] = self.dependents.get(dependent, 0) + 1
    TypeError: 'NoneType' object does not support item assignment

```

After debugging I found it is probably caused by the introduction of `_ImmutableDeclaration`. 
In `Specificaton` ..
https://github.com/zopefoundation/zope.interface/blob/489328a5afc1430a064db2dba7a7a408591789f9/src/zope/interface/interface.py#L228-L247
... `subscribe` and `unsubscribe` methods are defined which modifies `_dependents`, which is set deferred on first access.
In `_ImmutableDeclaration` a subclass of `Declaration` which is a subclass of above `Specification` ...
https://github.com/zopefoundation/zope.interface/blob/489328a5afc1430a064db2dba7a7a408591789f9/src/zope/interface/declarations.py#L148-L150
... the on-access creating property is overwritten, but subscribe and unsubscribe are still in place.

Code is calling subscribe in above traceback and it fails.

I still do not understand the difference of `IKeyReference` compared to other Interfaces here, it does not look special?
https://github.com/zopefoundation/zope.keyreference/blob/master/src/zope/keyreference/interfaces.py#L31

**Comment by jensens** [comment]
cc @jamadden

**Comment by jamadden** [comment]
Thank you, that's good news! I implemented it that way (leaving `subscribe`/`unsubscribe` unimplemented) specifically so that it would blow up if they were used on the empty declaration. Obviously the tests pass here, so there's a use-case we're not testing.

It may or may not be a bug that the adapter registry is subscribing to the empty singleton. In an application with a lot of adapter registries (sites) I could imagine that being a substantial memory use. Since the immutable declaration should never change, if we're truly using it correctly, we shouldn't need to track any dependents at all.

I'll have to write some tests and go through the code to re-create this use case in the zope.interface tree.

**Comment by jamadden** [comment]
At least this particular example is because of multiple corner-case error fallbacks happening at the same time (#163 details them). That explains why it's not caught by existing test cases.
