### ISSUE TITLE
 Method.'getSignatureString' refers 'zope.schema._bootstrapfields.Bool' instances instead of 'boolean' values

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.interface#17]
In https://bugs.launchpad.net/zope.interface/+bug/1079253, @kedder reported:

> Method.getSignatureString returns
>
    sorted(iterable, cmp=None, key=None, reverse=<zope.schema._bootstrapfields.Bool object at 0x2a768d0>)
>
> instead of
>
    sorted(iterable, cmp=None, key=None, reverse=False)

**Comment by jamadden** [comment]
I don't see anywhere that `zope.interface` itself defines an interface method `sorted` so I'm not sure what this could be referring to.

**Comment by tseaver** [comment]
`sorted` is a builtin.

**Comment by jamadden** [comment]
Yes, but `fromFunction` doesn't work on builtins:

```python
>>> import zope.interface.interface
>>> zope.interface.interface.fromFunction(sorted)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jmadden/Projects/VirtualEnvs/nti.schema27/lib/python2.7/site-packages/zope/interface/interface.py", line 616, in fromFunction
    code = func.__code__
AttributeError: 'builtin_function_or_method' object has no attribute '__code__'
```

I don't know how else to get a Method to represent that (actually, I'd never seen or used fromFunction until I started looking at this).

**Comment by tseaver** [comment]
I just tried it for an interface defined via a class statement:

```python
>>> from zope.interface import Interface
>>> class WithSorted(Interface):
...     def sorted(iterable, cmp=None, key=None, reverse=False):
...         pass
... 
>>> WithSorted.get('sorted').getSignatureString()
'(iterable, cmp=None, key=None, reverse=False)'
```

@kedder can you flesh out the report any further?  If so, please reopen.
