### ISSUE TITLE
Recent setuptools 46.0.0 update breaks latest released version

### ISSUE THREAD

**Issue by fmigneault** [zopefoundation/zope.interface#184]
Fix in https://github.com/zopefoundation/zope.interface/issues/30 should be ported back to pre `5.0.0.dev0` as current 'latest' release `4.7.1` breaks due to `setuptools 46.0.0` (https://github.com/pypa/setuptools/commit/c71969013d726c5cbd06dc81770ab064f3e783ff).

There is currently no released version that can be used, and I would prefer to avoid tagging `5.0.0.dev0` which is being worked on and very prone to upcoming issues.

**Comment by mgedmin** [comment]
Thank you for raising the alarm!

I've created a 4.7 branch that contains the deFeaturefication change and some travis/appveyor fixes, but none of the newer, riskier changes.

I intend to release it as 4.7.2 if the builds are green.

**Comment by mgedmin** [comment]
4.7.2 is out on PyPI, now we're waiting for Travis and Appveyor to create all the wheels.

**Comment by mgedmin** [comment]
All the wheels are built (except for Mac OS wheels for Python 3.8 but even git master doesn't have a .travis.yml snippet for those -- somebody maybe ought to copy and paste it from [persistent](https://github.com/zopefoundation/persistent/blob/ce84010b4c73556620ae8ca8c289d368d5fa1e04/.travis.yml#L91-L94)).

**Comment by fmigneault** [comment]
Thank you 👍
