### ISSUE TITLE
ImmutableDeclaration: Allows mutable _v_attrs

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.interface#204]
Some user code likes to assign to `_v_attrs` and/or write into the dictionary to piggyback on caching. Since ImmutableDeclaration provides no way to clear `_v_attrs` (it assumes it stays None), this can lead to incorrect results. 

This is not a regression in 5.0 but a pre-existing problem.

Proposal: Make `ImmutableDeclaration` use a property to always return a fresh dictionary for `_v_attrs`.

**Comment by jensens** [comment]
I am not sure if this is really helpful, since the attribute access should not go through extra cycles for the sake of speed?

**Comment by jamadden** [comment]
> I am not sure if this is really helpful, since the attribute access should not go through extra cycles for the sake of speed?

If I understand correctly, then perhaps a good solution to that is to override `get()` to simply return the default. No need to go to its parent implementation, by definition the immutable declaration has no declared Attributes.
