### ISSUE TITLE
Inconsistent resolution order

### ISSUE THREAD

**Issue by malinoff** [zopefoundation/zope.interface#21]
This best explained with the code below:

``` python
from zope.interface import Interface

def factory(O):
    class F(O): pass
    class E(O): pass
    class D(O): pass
    class C(D, F): pass
    class B(D, E): pass
    class A(B, C): pass
    return A

mro = [x.__name__ for x in factory(object).__mro__]
iro = [x.__name__ for x in factory(Interface).__iro__]
print('MRO', mro)
print('IRO', iro)
```

This code prints

``` python
MRO ['A', 'B', 'C', 'D', 'E', 'F', 'object']
IRO ['A', 'B', 'E', 'C', 'D', 'F', 'Interface']
```

You can see the inconsistency here, and mro is calculated correctly, of course.

```
$ pip freeze | grep zope
zope.interface==4.1.2
$ python --version
3.4.2
```

I tested on python 2.6.6 and got the same result.

**Comment by malinoff** [comment]
Anybody alive here?

**Comment by tseaver** [comment]
the IRO in zope.interface actually predates the introduction of MRO into Python itself.  Nobody else has found the current behavior problematic.  If you can supply a PR which fixes your issue, I'd be glad to review it (but backward-compatibility might preclude a merge).
