### ISSUE TITLE
5.1.0: do not install test

### ISSUE THREAD

**Issue by kloczek** [zopefoundation/zope.interface#210]
Is it any way to avoid installoing tests on demand?

**Comment by jamadden** [comment]
Not that I know of. Essentially all zope* packages I'm aware of include their tests. Downstream distributors (such as linux distributors) typically ask for that so that they can run the tests as part of their packaging process.

**Comment by jamadden** [comment]
There've been no updates for ~3 months; closing.

**Comment by kloczek** [comment]
Actually I just found that `zope.interface.tests` is used in `zope-interface` test suite ..
