### ISSUE TITLE
.meta.toml or the config template is out of sync with actual files

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.interface#245]
I ran the config-package.py from zopefoundation/meta and discovered that it makes unexpected changes:
- the entire `docs:` section gets removed from .github/workflows/tests.yml
- a `setenv = PURE_PYTHON=1` shows up in one of the tox testenv sections
- flake8 gets enabled unexpectedly, fixed in https://github.com/zopefoundation/meta/pull/111

and then the tool runs tox and half of the environments fail with mysterious `ModuleNotFoundError: No module named 'zope.testing'` errors.

This should not be happening.  It should be safe to re-generate the CI files from the template at any time without breaking anything.

I don't currently have the time/energy to look into this.

**Comment by icemac** [comment]
@mgedmin wrote:
> I ran the config-package.py from zopefoundation/meta and discovered that it makes unexpected changes:
> 
> * the entire `docs:` section gets removed from .github/workflows/tests.yml

Fixed in #250.

> * a `setenv = PURE_PYTHON=1` shows up in one of the tox testenv sections

This happens in the coverage section to make sure the pure Python code is covered with tests.

> * flake8 gets enabled unexpectedly, fixed in [Preserve [tox] flake8 meta#111](https://github.com/zopefoundation/meta/pull/111)

That was fixed over there.

> and then the tool runs tox and half of the environments fail with mysterious `ModuleNotFoundError: No module named 'zope.testing'` errors.

I did not see such errors.
