### ISSUE TITLE
Package name causes issues when combining requirements

### ISSUE THREAD

**Issue by Jorricks** [zopefoundation/zope.interface#255]
### What I did:
I created a small setup.py and listed a package that has zope-interface==5.4.0 as requirement. I used pip-tools to compile the package, which leads to `zope-interface==5.4.0` being added.
When I install the package I get
```
Requirement already satisfied: zope-interface==5.4.0 in /Users/jorrick/my_venv/lib/python3.8/site-packages (5.4.0)
```
Then when I try to run my entry_point console_scripts, I get
```
pkg_resources.DistributionNotFound: The 'zope-interface==5.4.0' distribution was not found and is required by adyen-airflow
```
But when I run pip3 freeze, I get
```
zope.interface==5.4.0
```

### What I expect to happen:
That I am able to run my CLI commands without issues

### What actually happened:
It throws a DistributionNotFound error.

### What version of Python and Zope/Addons I am using:
```
Python3.8
zope.event==4.5.0
zope.interface==5.4.0
```
on MacOs

**Comment by d-maurer** [comment]
Jorrick Sleijster wrote at 2022-3-11 02:14 -0800:
> ...
>### What I did:
>I created a small setup.py and listed a package that has zope-interface==5.4.0 as requirement. I used pip-tools to compile the package, which leads to `zope-interface==5.4.0` being added.

The package has the name `zope.interface` (not `zope-interface`).

**Comment by Jorricks** [comment]
Yess I think you are right and I need to take this up with `pip-tools` instead of this repository.

**Comment by Jorricks** [comment]
Opened https://github.com/jazzband/pip-tools/issues/1599 with `pip-tools`

**Comment by jamadden** [comment]
This is a constant struggle, because, according to [PEP 503](https://www.python.org/dev/peps/pep-0503/#normalized-names), `.` gets normalized away to `-` *for purposes of interacting with PyPI indexes*. But that normalization is often inconsistently applied or applied to places it shouldn't be.

```console
$ PIP_EXTRA_INDEX_URL= pip -vv index versions zope.interface
1 location(s) to search for versions of zope.interface:
* https://pypi.org/simple/zope-interface/
Fetching project page and analyzing links: https://pypi.org/simple/zope-interface/
Getting page https://pypi.org/simple/zope-interface/
...
```
