### ISSUE TITLE
The python 3.11 wheel for linux x86 is missing

### ISSUE THREAD

**Issue by wosc** [zopefoundation/zope.interface#264]
Similar to https://github.com/zopefoundation/persistent/issues/179, AFAICT there is only a linux/arm wheel on pypi currently (see https://pypi.org/project/zope.interface/5.5.2/#files), but no x86_64 one, for 3.11. (There is one for 3.10, though.) 

zope.interface does not error on install, it "just" will miss its C-based performance optimizations (which in some ways is more insiduous than an error message).

**Comment by icemac** [comment]
We are using the containers quay.io/pypa/manylinux2010_x86_64 resp. quay.io/pypa/manylinux2010_i686 to build the linux wheels. The lastest versions of that containers seem to contain Python 3.6 up to 3.10 as well as PyPy 3.7 and 3.8 but no Python 3.11.
Please create an issue at pypa, when this is fixed on their side we can rerun the release process to produce the missing wheels.

**Comment by vinayinvicible** [comment]
this is fixed in https://github.com/zopefoundation/persistent/issues/179. Can you please publish the missing wheels.

**Comment by icemac** [comment]
I just released https://pypi.org/project/zope.interface/6.0/ the wheels should be produced in the next couple of minutes.
