### ISSUE TITLE
Installing zope.interface 4.1.3 via setuptools.setup eats all memory

### ISSUE THREAD

**Issue by georgevreilly** [zopefoundation/zope.interface#28]
When I install zope.interface 4.1.3 implicitly using `setuptools.setup()`, I run out of memory in my Docker container on a 24GB host after a minute of high CPU utilization. When I install it explicitly via `pip install zope.interface`, it installs immediately without consuming a pile of resources.

    root@76fd4425ad19:/application/pycommon# python setup.py --verbose develop  
    {'entry_points': {console_scripts': [<OMITTED>]}, 'description': 'CookBrite Common Code', 'author': 'CookBrite', 'install_requires': ['sh', 'boto>=2.30.0', 'contexttimer', 'datadog==0.1.1', 'Mako>=0.4.1', 'MarkupSafe>=0.9.2', 'Werkzeug>=0.9.6', 'Pillow==2.7.0', 'pint', 'protobuf==2.5.0', 'pyramid>=1.5', 'pytz', 'requests==2.5.1', 'setuptools', 'simplejson', 'SQLAlchemy==0.9.9', 'SQLAlchemy-Utils==0.29.8', 'sqltap>=0.3.10', 'pip2pi>=0.6.4', 'python-magic', 'rollbar', 'nose', 'urllib3<1.11'], 'include_package_data': True, 'url': 'http://www.CookBrite.com/', 'author_email': 'ci@cookbrite.com', 'version': '0.3.0', 'zip_safe': False, 'keywords': 'build utility', 'packages': ['tests', 'cbcommon', 'tests.unit', 'tests.test_data', 'tests.unit.auth', 'tests.unit.ocr', 'tests.unit.resource', 'tests.unit.utils', 'tests.unit.aws', 'tests.unit.pkg', 'tests.unit.logic', 'tests.unit.ocr.merchant_identifier', 'tests.unit.aws.s3', 'tests.unit.aws.sqs', 'cbcommon.ocr', 'cbcommon.fabfile', 'cbcommon.api', 'cbcommon.client', 'cbcommon.security', 'cbcommon.resource', 'cbcommon.utils', 'cbcommon.aws', 'cbcommon.protobufs', 'cbcommon.pkg', 'cbcommon.logic', 'cbcommon.client.ocr', 'cbcommon.client.hub', 'cbcommon.client.test', 'cbcommon.utils.pb', 'cbcommon.aws.s3', 'cbcommon.aws.sqs'], 'classifiers': ['Programming Language :: Python'], 'name': 'cbcommon'}
    running develop
    running egg_info
    writing requirements to cbcommon.egg-info/requires.txt
    writing cbcommon.egg-info/PKG-INFO
    writing top-level names to cbcommon.egg-info/top_level.txt
    writing dependency_links to cbcommon.egg-info/dependency_links.txt
    writing entry points to cbcommon.egg-info/entry_points.txt
    reading manifest file 'cbcommon.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.ini'
    warning: no files found matching '*.cfg'
    writing manifest file 'cbcommon.egg-info/SOURCES.txt'
    running build_ext
    Creating /usr/local/lib/python2.7/site-packages/cbcommon.egg-link (link to .)
    cbcommon 0.3.0 is already the active version in easy-install.pth
    Installing <SOME> script to /usr/local/bin

    Installed /application/pycommon
    Processing dependencies for cbcommon==0.3.0
    Searching for zope.interface>=3.8.0
    Reading https://pypi.python.org/simple/zope.interface/
    Found link: https://pypi.python.org/packages/2.4/z/zope.interface/zope.interface-3.3.0-py2.4-win32.egg#md5=9eff742b077859f5381d43b15f2723f1
    <SNIP 300 LINES>
    Found link: https://pypi.python.org/packages/source/z/zope.interface/zope.interface-4.1.3.tar.gz#md5=9ae3d24c0c7415deb249dd1a132f0f79
    Best match: zope.interface 4.1.3
    Downloading https://pypi.python.org/packages/source/z/zope.interface/zope.interface-4.1.3.tar.gz#md5=9ae3d24c0c7415deb249dd1a132f0f79
    Validating md5 checksum for /tmp/easy_install-pAVzaI/zope.interface-4.1.3.tar.gz
    Processing zope.interface-4.1.3.tar.gz
    Unpacking zope.interface-4.1.3 to /tmp/easy_install-pAVzaI/zope.interface-4.1.3
    Unpacking zope.interface-4.1.3/COPYRIGHT.txt to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/COPYRIGHT.txt
    Unpacking zope.interface-4.1.3/.coveragerc to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/.coveragerc
    Unpacking zope.interface-4.1.3/bootstrap.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/bootstrap.py
    Unpacking zope.interface-4.1.3/MANIFEST.in to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/MANIFEST.in
    Unpacking zope.interface-4.1.3/README.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/README.rst
    Unpacking zope.interface-4.1.3/CHANGES.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/CHANGES.rst
    Unpacking zope.interface-4.1.3/tox.ini to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/tox.ini
    Unpacking zope.interface-4.1.3/setup.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/setup.py
    Unpacking zope.interface-4.1.3/setup.cfg to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/setup.cfg
    Unpacking zope.interface-4.1.3/PKG-INFO to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/PKG-INFO
    Unpacking zope.interface-4.1.3/LICENSE.txt to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/LICENSE.txt
    Unpacking zope.interface-4.1.3/buildout.cfg to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/buildout.cfg
    Unpacking zope.interface-4.1.3/docs to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs
    Unpacking zope.interface-4.1.3/docs/conf.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/conf.py
    Unpacking zope.interface-4.1.3/docs/adapter.ru.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/adapter.ru.rst
    Unpacking zope.interface-4.1.3/docs/foodforthought.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/foodforthought.rst
    Unpacking zope.interface-4.1.3/docs/_static to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/_static
    Unpacking zope.interface-4.1.3/docs/_static/.gitignore to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/_static/.gitignore
    Unpacking zope.interface-4.1.3/docs/verify.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/verify.rst
    Unpacking zope.interface-4.1.3/docs/api.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/api.rst
    Unpacking zope.interface-4.1.3/docs/hacking.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/hacking.rst
    Unpacking zope.interface-4.1.3/docs/README.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/README.rst
    Unpacking zope.interface-4.1.3/docs/adapter.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/adapter.rst
    Unpacking zope.interface-4.1.3/docs/human.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/human.rst
    Unpacking zope.interface-4.1.3/docs/human.ru.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/human.ru.rst
    Unpacking zope.interface-4.1.3/docs/index.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/index.rst
    Unpacking zope.interface-4.1.3/docs/Makefile to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/Makefile
    Unpacking zope.interface-4.1.3/docs/make.bat to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/make.bat
    Unpacking zope.interface-4.1.3/docs/README.ru.rst to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/docs/README.ru.rst
    Unpacking zope.interface-4.1.3/src to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src
    Unpacking zope.interface-4.1.3/src/zope.interface.egg-info to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope.interface.egg-info
    Unpacking zope.interface-4.1.3/src/zope.interface.egg-info/dependency_links.txt to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope.interface.egg-info/dependency_links.txt
    Unpacking zope.interface-4.1.3/src/zope.interface.egg-info/PKG-INFO to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope.interface.egg-info/PKG-INFO
    Unpacking zope.interface-4.1.3/src/zope.interface.egg-info/not-zip-safe to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope.interface.egg-info/not-zip-safe
    Unpacking zope.interface-4.1.3/src/zope.interface.egg-info/requires.txt to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope.interface.egg-info/requires.txt
    Unpacking zope.interface-4.1.3/src/zope.interface.egg-info/SOURCES.txt to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope.interface.egg-info/SOURCES.txt
    Unpacking zope.interface-4.1.3/src/zope.interface.egg-info/pbr.json to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope.interface.egg-info/pbr.json
    Unpacking zope.interface-4.1.3/src/zope.interface.egg-info/namespace_packages.txt to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope.interface.egg-info/namespace_packages.txt
    Unpacking zope.interface-4.1.3/src/zope.interface.egg-info/top_level.txt to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope.interface.egg-info/top_level.txt
    Unpacking zope.interface-4.1.3/src/zope to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope
    Unpacking zope.interface-4.1.3/src/zope/__init__.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/__init__.py
    Unpacking zope.interface-4.1.3/src/zope/interface to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface
    Unpacking zope.interface-4.1.3/src/zope/interface/_compat.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/_compat.py
    Unpacking zope.interface-4.1.3/src/zope/interface/interfaces.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/interfaces.py
    Unpacking zope.interface-4.1.3/src/zope/interface/document.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/document.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_element.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_element.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_odd_declarations.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_odd_declarations.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_document.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_document.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_adapter.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_adapter.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_declarations.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_declarations.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/m2.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/m2.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/advisory_testing.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/advisory_testing.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/idummy.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/idummy.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/__init__.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/__init__.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/odd.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/odd.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_interface.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_interface.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/ifoo.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/ifoo.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_interfaces.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_interfaces.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/dummy.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/dummy.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_registry.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_registry.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_exceptions.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_exceptions.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_sorting.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_sorting.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/ifoo_other.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/ifoo_other.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_advice.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_advice.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_ro.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_ro.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/test_verify.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/test_verify.py
    Unpacking zope.interface-4.1.3/src/zope/interface/tests/m1.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/tests/m1.py
    Unpacking zope.interface-4.1.3/src/zope/interface/ro.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/ro.py
    Unpacking zope.interface-4.1.3/src/zope/interface/__init__.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/__init__.py
    Unpacking zope.interface-4.1.3/src/zope/interface/advice.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/advice.py
    Unpacking zope.interface-4.1.3/src/zope/interface/_zope_interface_coptimizations.c to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/_zope_interface_coptimizations.c
    Unpacking zope.interface-4.1.3/src/zope/interface/declarations.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/declarations.py
    Unpacking zope.interface-4.1.3/src/zope/interface/common to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/common
    Unpacking zope.interface-4.1.3/src/zope/interface/common/interfaces.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/common/interfaces.py
    Unpacking zope.interface-4.1.3/src/zope/interface/common/tests to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/common/tests
    Unpacking zope.interface-4.1.3/src/zope/interface/common/tests/test_idatetime.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/common/tests/test_idatetime.py
    Unpacking zope.interface-4.1.3/src/zope/interface/common/tests/basemapping.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/common/tests/basemapping.py
    Unpacking zope.interface-4.1.3/src/zope/interface/common/tests/__init__.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/common/tests/__init__.py
    Unpacking zope.interface-4.1.3/src/zope/interface/common/tests/test_import_interfaces.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/common/tests/test_import_interfaces.py
    Unpacking zope.interface-4.1.3/src/zope/interface/common/mapping.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/common/mapping.py
    Unpacking zope.interface-4.1.3/src/zope/interface/common/__init__.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/common/__init__.py
    Unpacking zope.interface-4.1.3/src/zope/interface/common/sequence.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/common/sequence.py
    Unpacking zope.interface-4.1.3/src/zope/interface/common/idatetime.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/common/idatetime.py
    Unpacking zope.interface-4.1.3/src/zope/interface/interface.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/interface.py
    Unpacking zope.interface-4.1.3/src/zope/interface/adapter.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/adapter.py
    Unpacking zope.interface-4.1.3/src/zope/interface/verify.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/verify.py
    Unpacking zope.interface-4.1.3/src/zope/interface/exceptions.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/exceptions.py
    Unpacking zope.interface-4.1.3/src/zope/interface/registry.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/registry.py
    Unpacking zope.interface-4.1.3/src/zope/interface/_flatten.py to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/src/zope/interface/_flatten.py
    Unpacking zope.interface-4.1.3/rtd.txt to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/rtd.txt
    Reading configuration from /tmp/easy_install-pAVzaI/zope.interface-4.1.3/setup.cfg
    Adding new section [easy_install] to /tmp/easy_install-pAVzaI/zope.interface-4.1.3/setup.cfg
    Writing /tmp/easy_install-pAVzaI/zope.interface-4.1.3/setup.cfg
    Running zope.interface-4.1.3/setup.py bdist_egg --dist-dir /tmp/easy_install-pAVzaI/zope.interface-4.1.3/egg-dist-tmp-TiDo4R
    running bdist_egg
    running egg_info
    writing requirements to src/zope.interface.egg-info/requires.txt
    writing src/zope.interface.egg-info/PKG-INFO
    writing namespace_packages to src/zope.interface.egg-info/namespace_packages.txt
    writing top-level names to src/zope.interface.egg-info/top_level.txt
    writing dependency_links to src/zope.interface.egg-info/dependency_links.txt
    Traceback (most recent call last):
      File "setup.py", line 25, in <module>
        setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/command/develop.py", line 32, in run
        self.install_for_development()
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/command/develop.py", line 132, in install_for_development
        self.process_distribution(None, self.dist, not self.no_deps)
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 709, in process_distribution
        [requirement], self.local_index, self.easy_install
      File "/usr/local/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "/usr/local/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1093, in obtain
        return installer(requirement)
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1056, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 240, in run_setup
        raise
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 152, in save_modules
        yield saved
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 126, in __exit__
        self._saved = UnpickleableException.dump(type, exc)
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
      File "/usr/local/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 110, in dump
        return cls.dump(cls, cls(repr(exc)))
    MemoryError

If I then install directly with pip, it promptly succeeds

    root@76fd4425ad19:/application/pycommon# pip install 'zope.interface>=3.8.0'
    Collecting zope.interface>=3.8.0
    Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages (from zope.interface>=3.8.0)
    Installing collected packages: zope.interface
    Successfully installed zope.interface-4.1.3

Now my `setup.py` succeeds

    root@76fd4425ad19:/application/pycommon# python setup.py --verbose develop  
    <SUCCEEDS>

    root@0516ca7860de:/# pip freeze            
    boto==2.38.0
    cbcommon==0.3.0
    contexttimer==0.3.1
    cornice==0.18.2
    Cython==0.23.4
    datadog==0.1.1
    decorator==4.0.4
    ebs-deploy===1.7-cookbrite-wait-time-b
    ecdsa==0.11
    Fabric==1.9.0
    httpretty==0.8.3
    Mako==1.0.3
    MarkupSafe==0.23
    nose==1.3.7
    numpy==1.9.0
    paramiko==1.14.0
    PasteDeploy==1.5.2
    Pillow==2.7.0
    Pint==0.6
    pip2pi==0.6.8
    protobuf==2.5.0
    pycrypto==2.6.1
    pyramid==1.6a2
    python-magic==0.4.10
    python-tesseract==0.9
    pytz==2015.7
    PyYAML==3.11
    repoze.lru==0.6
    requests==2.5.1
    rollbar==0.11.0
    scikit-image==0.10.1
    scipy==0.14.0
    sh==1.11
    simplejson==3.8.1
    six==1.7.3
    SQLAlchemy==0.9.9
    SQLAlchemy-Utils==0.29.8
    sqlparse==0.1.18
    sqltap==0.3.10
    translationstring==1.3
    urllib3==1.10.4
    venusian==1.0
    virtualenv==13.1.2
    WebOb==1.5.1
    Werkzeug==0.11.1
    wheel==0.24.0
    zope.deprecation==4.1.2
    zope.interface==4.1.3

This is completely reproducible on my host and containers (all Ubuntu 14.04). GCC 4.8.4 is present in the container.

**Comment by mgedmin** [comment]
Looks like a setuptools bug to me -> https://bitbucket.org/pypa/setuptools/issues

**Comment by georgevreilly** [comment]
Yes, Setuptools [#440](https://bitbucket.org/pypa/setuptools/issues/440/unpickleableexceptiondump-blows-up-when) and [#448](https://bitbucket.org/pypa/setuptools/issues/448/develop-mode-in-anaconda-environment) seem quite similar.

**Comment by mgedmin** [comment]
So it looks two bugs for the price of one:
- something causes a SandboxViolation (or some other kind of exception)
- then error handling code in setuptools bombs out, unfortunately obscuring the 1st bug.

It's hard to say at this point if the first bug is a bug in setuptools, or if it's actually zope.interface's setup.py doing something wrong.

**Comment by mgedmin** [comment]
BTW does `pip install -e .` work?  It should be equivalent to `python setup.py develop`, except with more metadata kept for a possible future `pip uninstall`.

**Comment by georgevreilly** [comment]
Yes! `pip install -e .` works correctly and quickly.

    root@6bcfbc698931:/application/pycommon# pip uninstall -y zope.interface
    Uninstalling zope.interface-4.1.3:
      Successfully uninstalled zope.interface-4.1.3

    root@6bcfbc698931:/application/pycommon# python -c 'import zope.interface' && echo "installed"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named interface

    root@6bcfbc698931:/application/pycommon# time pip install -e .
    Obtaining file:///application/pycommon
    Requirement already satisfied (use --upgrade to upgrade): sh in /usr/local/lib/python2.7/site-packages/sh-1.11-py2.7.egg (from cbcommon==0.3.0)
    ...
    Collecting zope.interface>=3.8.0 (from pyramid>=1.5->cbcommon==0.3.0)
    ...
    Requirement already satisfied (use --upgrade to upgrade): sqlparse>=0.1.15 in /usr/local/lib/python2.7/site-packages/sqlparse-0.1.18-py2.7.egg (from sqltap>=0.3.10->cbcommon==0.3.0)
    Installing collected packages: cbcommon, zope.interface
      Running setup.py develop for cbcommon
    Successfully installed cbcommon-0.3.0 zope.interface-4.1.3

    real    0m1.579s
    user    0m1.004s
    sys 0m0.568s

    root@6bcfbc698931:/application/pycommon# python -c 'import zope.interface' && echo "installed"
    installed

**Comment by jamadden** [comment]
This was reported fixed in setuptools 18. Can that be confirmed and this issue closed?

**Comment by tseaver** [comment]
I never figured out how to reproduce it.  @georgevreilly, can you confirm?

**Comment by georgevreilly** [comment]
This no longer reproes for me.
