### ISSUE TITLE
Any plans to publish macos `universal2` wheels?

### ISSUE THREAD

**Issue by carlos-villavicencio-adsk** [zopefoundation/zope.interface#287]
## BUG/PROBLEM REPORT / FEATURE REQUEST

I'm currently working on a desktop project that bundles zope.interface. We're doing the required changes to run natively on Apple Silicon processors.

By inspecting the installed files I realized that `_zope_interface_coptimizations.cpython-310-darwin.so` architecture is only `x86_64`.

So, as the title says, are there any plans to publish universal2 wheels? Can you recommend any workaround?

### What I did:

On a macos intel computer:
```
$ pip install zope.interface==5.5.2
```
Then build and package my application.

On a macos apple silicon computer:
```
$ lipo -archs path/to/zope/interface/_zope_interface_coptimizations.cpython-310-darwin.so
```

### What I expect to happen:

```
x86_64 arm64
```

### What actually happened:

```
x86_64
```

### What version of Python and Zope/Addons I am using:

- MacOS 12 Intel (build machine)
- MacOS 14 M1 (client machine)
- Python 3.10.13
- zope.interface==5.5.2

**Comment by icemac** [comment]
Nice to hear, so I am closing this issue now.
