### ISSUE TITLE
Wheel building process produces no Windows wheels

### ISSUE THREAD

**Issue by dataflake** [zopefoundation/zope.interface#295]
Release 6.4 has no Windows wheels for some reason, I had to revert to version 6.3 on Zope master to make release 5.10.

**Comment by dataflake** [comment]
The test run on tag 6.4 (https://github.com/zopefoundation/zope.interface/actions/runs/9102178342) shows Windows wheels in the artifacts list but they didn't make it to PyPI for some reason.

**Comment by dataflake** [comment]
So it looks like the current meta templates simply don't have a PyPI upload step for Windows wheels. There's explicit ones for macOS and for manylinux wheels. But none that match Windows.

**Comment by icemac** [comment]
See also #298.
