### ISSUE TITLE
"Features are deprecated and will be removed in a future version"

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.interface#30]
Building zope.interface produces these deprecation warnings from setuptools:

```
setup.py:77: DeprecationWarning: Features are deprecated and will be removed in a future version. See http://bitbucket.org/pypa/setuptools/65.
  [os.path.normcase(codeoptimization_c)]
c:\python26\Lib\distutils\core.py:113: DeprecationWarning: Features are deprecated and will be removed in a future version. See http://bitbucket.org/pypa/setuptools/65.
  _setup_distribution = dist = klass(attrs)
```

http://bitbucket.org/pypa/setuptools/65 is, ha ha, a 404 page.

**Comment by mgedmin** [comment]
https://bitbucket.org/pypa/setuptools/issues/65 is the correct link.

It claims Features have been removed in early 2014?  Clearly I'm missing something.

**Comment by tseaver** [comment]
The issue is [migrated to Github](https://github.com/pypa/setuptools/issues/65), where it is still open:  they backed out the change after discovering the vast amount of breakage induced by dropping it.

**Comment by jaraco** [comment]
Thanks Tres for pinging this to the ticket - it gives me the opportunity to let this project know that its package will stop building from source in a near-future backward-incompatible Setuptools release.
