### ISSUE TITLE
With Python 3.5: "TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead."

### ISSUE THREAD

**Issue by gustavklopp** [zopefoundation/zope.interface#32]
The problem is on the line apparently: 

https://github.com/zopefoundation/zope.interface/blob/master/src/zope/interface/declarations.py#L412
```
   File "/home/gus/.Envs/python3.5_kivy/lib/python3.5/site-packages/twisted/internet/_threadedselect.py", line 82, in ThreadedSelectReactor
     implements(IReactorFDSet)
   File "/home/gus/.Envs/python3.5_kivy/lib/python3.5/site-packages/zope/interface/declarations.py", line 412, in implements
     raise TypeError(_ADVICE_ERROR % 'implementer')
 TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.
```

**Comment by jamadden** [comment]
The problem is not in zope.interface, it's in the caller. In this case twisted.internet._threadedselect is using the outdated form. Perhaps it has an update?

**Comment by gustavklopp** [comment]
Okay, thanks for the tip! There are indeed compatibility problems noted in the docs for Twisted. I will see how to adapt Twisted code
