### ISSUE TITLE
Different name of source distribution on PyPI

### ISSUE THREAD

**Issue by frenzymadness** [zopefoundation/zope.interface#329]
Hi.

The latest release has a different name of the source distribution on PyPI than the previous version had:

```
zope.interface-7.0.3.tar.gz
zope_interface-7.1.0.tar.gz
```

Was that intentional? If so, feel free to close this issue.

**Comment by icemac** [comment]
The second variant is produced by newer versions of `setuptools`. `zc.buildout` had problems recognizing them but this should be solved by the latest versions. So there is not reason to keep using the old format any more.
