### ISSUE TITLE
setuptools version limit

### ISSUE THREAD

**Issue by frenzymadness** [zopefoundation/zope.interface#333]
What is the reason to limit the version of setuptools to:

https://github.com/zopefoundation/zope.interface/blob/7e0be48d15c594cc592537da2da98311017b19ab/pyproject.toml#L6

It seems to me that it builds fine also with setuptools 74.1.3

**Comment by d-maurer** [comment]
frenzymadness wrote at 2024-10-27 12:34 -0700:
>What is the reason to limit the version of setuptools to:
>
>https://github.com/zopefoundation/zope.interface/blob/7e0be48d15c594cc592537da2da98311017b19ab/pyproject.toml#L6
>
>It seems to me that it builds fine also with setuptools 74.1.3

The `setuptools` requirement comes from
https://github.com/zopefoundation/meta/pull/274

Many `zopefoundation` projects use `zc.buildout` to build
test environments. Apparently, (see PR mentioned above), new
`setuptools` versions tend to be incompatible with older `zc.buildout`
versions. The `zc.buildout` maintenance is not very active; therefore,
it can take significant time until a new version compatible with
newer `setuptools` becomes available.


I might be possible that `zope.interface` does not use itself
`zc.buildout` for its testing. However, many parts
(among them  the `setuptools` requirement) are generated from a common
base used for all `zopefoundation` projects.

**Comment by esaaprillia** [comment]
I am using setuptools version 75.6 and getting setuptools version mismatch. To solve this I removed the setuptools version.

**Comment by icemac** [comment]
See https://github.com/zopefoundation/meta/pull/292 for reference.

**Comment by mauritsvanrees** [comment]
> I am using setuptools version 75.6 and getting setuptools version mismatch. To solve this I removed the setuptools version.
> 
> ```
> ERROR Missing dependencies:
> setuptools<74
> ```

This limit on the setuptools requirement is only active when building the zope.interface package.  It should be no problem to have a Python venv with setuptools 75 and still install zope.interface.  But this depends on how you build or install it and especially whether that is in isolation or not.  For example:

```
$ python3.13 -mvenv test
$ cd test
$ bin/pip install -U pip setuptools build
$ bin/pip freeze --all
build==1.2.2.post1
packaging==24.2
pip==24.3.1
pyproject_hooks==1.2.0
setuptools==75.6.0
$ bin/python -m build --no-isolation /path/to/zope.interface/
...
ERROR Missing dependencies:
	setuptools<74
$ bin/python -m build /path/to/zope.interface/
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - setuptools < 74
...
Successfully built zope_interface-7.3.dev0.tar.gz
 and zope.interface-7.3.dev0-cp313-cp313-macosx_14_0_x86_64.whl
```
