### ISSUE TITLE
please build wheels instead of eggs for binary distribution on win32

### ISSUE THREAD

**Issue by glyph** [zopefoundation/zope.interface#39]
Pip can't install binary eggs, but it can install wheels.

This should be as simple as `python setup.py bdist_wheel; twine upload dist/*`.

**Comment by glyph** [comment]
(This blocks the ability of Twisted to be installed without a C compiler with `pip`, despite the fact that we build our own wheels, so I'm keen to get this fixed!)

**Comment by tseaver** [comment]
We can't build `none-any` wheels for this package:  we need to build platform-specific wheels for OS/X and Windows.  See #37 for the effort to automate that process via Travis and Appveyor.

**Comment by glyph** [comment]
@tseaver - that is indeed what I would have expected; thanks for the pointer.

**Comment by fgregg** [comment]
@glyph we are working on building wheels, but zope interface should be able to be installed right now without a compiler.  That's what https://github.com/zopefoundation/zope.interface/blob/master/setup.py#L35 is attempting to do. Does that not work for you?

**Comment by jamadden** [comment]
Setting the environment variable `PURE_PYTHON` bypasses any attempt to even *try* to compile C extensions for zope.interface and many other zope projects.

**Comment by glyph** [comment]
@fgregg - I guess I was seeing a compiler get invoked, and assuming it would be invoked unconditionally.  I will investigate some more later, to see if I can get it to fail, but I think you're right.

**Comment by prsephton** [comment]
Will existing projects which use buildout continue to function if you
change from eggs to wheels?

**Comment by tseaver** [comment]
@prsephton 

> Will existing projects which use buildout continue to function if you change from eggs to wheels?

On Linux systems, and Mac Systems with compilers, sure:  `zope.interface` is trivial to compile.  On Windows, not so much.  Buildout will need to grow support for installing wheels (see https://github.com/buildout/buildout/issues/144).

**Comment by prsephton** [comment]
Ty for the answer

**Comment by tseaver** [comment]
Wheels for Windows and MacOS now automated through Travis/Appveyor via PR #37.
