### ISSUE TITLE
Document AdapterRegistry inside the API docs

### ISSUE THREAD

**Issue by adiroiban** [zopefoundation/zope.interface#41]
AdapterRegistry is documented in the narrative docs at https://docs.zope.org/zope.interface/adapter.html 

but it is not documented as part of the API page https://docs.zope.org/zope.interface/api.html

It would be nice to have it documented in the API so that external documentation can link to it using inter-sphinx links.

For example in Twisted `L{zope.interface.adapter.AdapterRegistry}` is used to create a link from Twisted API docs to zope.interface API docs ... but the link resolution fails. 

 `L{zope.interface.declarations.implementer}` works as it is documented on the API page.

See  https://github.com/twisted/twisted/pull/238

Thanks!

**Comment by jamadden** [comment]
It is well documented [in the code](https://github.com/zopefoundation/zope.interface/blob/master/src/zope/interface/interfaces.py#L664).

The documentation conf.py [does include repoze.sphinx.autointerface](https://github.com/zopefoundation/zope.interface/blob/master/docs/conf.py#L35), so it should just be a matter of adding an `interfaces.rst` with the correct `..automodule` directive to the TOC.
