### ISSUE TITLE
Make declarations.Implements (and possibly Provides) comparable?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.interface#42]
Recently we had the need to do some `IComponents`-like things on some very large persistent data sets. So we started with a subclass of `AdapterRegistry` and made it use BTrees instead of dicts. Everything works fine so long as you stay in the realm of interfaces, but as soon as you try to do something based on classes, like `components.registerAdapter(factory, provided=IFoo, required=(str,))`  you blow up with `TypeError: Object has default comparison`. 

Actually it's slightly worse than that. Some of the dicts used in the implementation of Components (which we also replaced with BTrees) use keys that are tuples. Tuples are automatically comparable, even if their elements aren't. But having non-comparable keys (or rather, keys that change across processes) is a sure way to corrupt the BTree.

I looked into it, and was pretty surprised to find that not only are `Implements` and `Provides` not comparable, they actually rely on the default, identity-based, `__hash__` and `__eq__` inherited from object. Everything pretty much happens to work out for a regular `PersistentAdapterRegistry` because of the way these objects are pickled (in Implement's case, via `__reduce__` and a call to `implementedBy`, which aggressively caches the same object, so identities stay the same in a single process even across pickling).

Is it a bad idea to make `Implements` comparable so it can be used in BTrees? To work for the `IComponents` use-case, it would have to be mutually-comparable with `InterfaceClass`, but it already has `__name__` and `__module__` (which is what `InterfaceClass` uses), so that might just work out nearly automatically.

If there's consensus this is a reasonable idea, I can work on a PR. (In our particular use-case, we were able to simply prohibit class-based registrations as they don't occur in our data set.)

**Comment by tseaver** [comment]
The notion seems reasonable to me.  I don't see any backward-compatibilty issues.

**Comment by jamadden** [comment]
One thought I had was about performance.  Implementing `__eq__` is going to have a cost over using the default identity-based implementation. Simply overriding it to do identity comparison makes it more than twice as slow:
```python
In [1]: class WithEq(object):
   ...:     def __eq__(self, other):
   ...:         return other is self
   ...:

In [2]: class NoEq(object): pass

In [3]: noeq = NoEq()

In [4]: witheq = WithEq()

In [5]: %timeit noeq == noeq
The slowest run took 19.87 times longer than the fastest. ...
10000000 loops, best of 3: 108 ns per loop

In [6]: %timeit witheq == witheq
The slowest run took 10.28 times longer than the fastest. ...
1000000 loops, best of 3: 278 ns per loop
```

We'll also need to override `__hash__` so that it's consistent with the `__eq__` definition and that seems to take an even bigger hit:
```python
In [9]: class WithHash(object):
   ...:     def __hash__(self):
   ...:         return 1
   ...:

In [10]: class NoHash(object): pass

In [11]: withhash = WithHash()

In [12]: nohash = NoHash()

In [13]: %timeit hash(withhash)
The slowest run took 13.90 times longer than the fastest. ...
1000000 loops, best of 3: 223 ns per loop

In [14]: %timeit hash(nohash)
The slowest run took 25.18 times longer than the fastest. ...
10000000 loops, best of 3: 85.2 ns per loop
```

Hopefully this isn't actually a problem...
