### ISSUE TITLE
test_sorting.py fail

### ISSUE THREAD

**Issue by wljjn** [zopefoundation/zope.interface#58]
When I run test_sorting.py, it fails with message as below.
```
FAIL: test_w_equal_names (__main__.Test)
Traceback (most recent call last):
  File "src/zope/interface/tests/test_sorting.py", line 47, in test_w_equal_names
    self.assertEqual(l, [m1_I1, I1])
AssertionError: Lists differ: [<InterfaceClass __main__.I1>,... != [<InterfaceClass zope.interfac...
```
I printed the interface modules and they are `__main__` and zope.interface.tests.m1. It looks to me that `__main__` should be before zope.interface.tests.m1, which means I1 should be before m1_I1 when sorting completes. So I wonder how does a successful test work?

**Comment by jamadden** [comment]
I guess you're running that test with something like `python -m zope.interface.tests.test_sorting`.

But as you noticed, it doesn't work that way. 

You need to use a testrunner, for example: `zope-testrunner --test-path=src test_sorting -vvvv`

**Comment by wljjn** [comment]
Thank you, that helps!

**Comment by mgedmin** [comment]
Perhaps let's remove the [`if __name__ == '__main__':`](https://github.com/zopefoundation/zope.interface/blob/master/src/zope/interface/tests/test_sorting.py#L54-L55) part from test files if that's not supposed to work?

**Comment by jamadden** [comment]
Or maybe add `@unittest.skipIf(__name__ == '__main__')` to that test.

It appears the `if __name__ == '__main__'` block predates `test_w_equal_names` by about 4 years (2007 vs 2011).
