### ISSUE TITLE
C optimizations

### ISSUE THREAD

**Issue by bloodbare** [zopefoundation/zope.interface#60]
When we are loading zope.interface on our projects the coptimizations are not loaded saying:

ImportError: No module named '_zope_interface_coptimizations'

If we change the import to zope.interface._zope_interface_coptimizations it works.

Python 3.5

**Comment by jinty** [comment]
I made a branch for this, unfortunately a lot of tests fail with:

SystemError: Bad call flags in PyCFunction_Call. METH_OLDARGS is no longer supported!

when the optimizations are actually loaded

**Comment by tseaver** [comment]
@jinty the bug you are seeing is described [here](http://bugs.python.org/issue15657).  The following patch fixes it:

```
--- a/src/zope/interface/_zope_interface_coptimizations.c
+++ b/src/zope/interface/_zope_interface_coptimizations.c
@@ -25,6 +25,15 @@
 #define Py_TYPE(o) ((o)->ob_type)
 #endif
 
+#if PY_MAJOR_VERSION >= 3
+#define PY3K
+#endif
+
+#ifdef PY3K
+/* See http://bugs.python.org/issue15657 */
+#define METH_KEYWORDS 0x0003
+#endif
+
 static PyObject *str__dict__, *str__implemented__, *strextends;
 static PyObject *BuiltinImplementationSpecifications, *str__provides__;
 static PyObject *str__class__, *str__providedBy__;
```



BTW, I think we should be using absolute, rather than relative, imports.

**Comment by bloodbare** [comment]
Agree on having absolute imports.

**Comment by jinty** [comment]
@tseaver thanks for carrying this on. I've deleted my branch.

I'm curious, why the preference for absolute imports?

On Tue, Nov 15, 2016 at 08:54:30AM -0800, Tres Seaver wrote:
> @jinty the bug you are seeing is described [here](http://bugs.python.org/issue15657).  The following patch fixes it:
> 
> ```
> --- a/src/zope/interface/_zope_interface_coptimizations.c
> +++ b/src/zope/interface/_zope_interface_coptimizations.c
> @@ -25,6 +25,15 @@
>  #define Py_TYPE(o) ((o)->ob_type)
>  #endif
>  
> +#if PY_MAJOR_VERSION >= 3
> +#define PY3K
> +#endif
> +
> +#ifdef PY3K
> +/* See http://bugs.python.org/issue15657 */
> +#define METH_KEYWORDS 0x0003
> +#endif
> +
>  static PyObject *str__dict__, *str__implemented__, *strextends;
>  static PyObject *BuiltinImplementationSpecifications, *str__provides__;
>  static PyObject *str__class__, *str__providedBy__;
> ```
> 
> 
> 
> BTW, I think we should be using absolute, rather than relative, imports.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/zopefoundation/zope.interface/issues/60#issuecomment-260698507

-- 
Brian Sutherland

**Comment by bloodbare** [comment]
@tseaver can we have a release with this solution ?

**Comment by tseaver** [comment]
@bloodbare [4.3.3 released](https://pypi.python.org/pypi/zope.interface/4.3.3).
