### ISSUE TITLE
License not included in install from PyPi

### ISSUE THREAD

**Issue by altendky** [zopefoundation/zope.interface#62]
![image](https://cloud.githubusercontent.com/assets/543719/20352138/41837fde-abe4-11e6-8463-dfbdabc127fd.png)

I was going through the libraries I use to collect licenses since I distribute my application using `pyqtdeploy` on Windows and noticed that `zope.interface` did not seem to include it's own license when installed from PyPi.

**Comment by tseaver** [comment]
I just looked at the PyPI page:  https://pypi.python.org/pypi/zope.interface#downloads.  The `zope.interface-4.3.2.tar.gz` file there *does* include its `LICENSE.txt` file.  That file is packaging metadata, and is not installed into `site-packages` (nor will it be).

**Comment by altendky** [comment]
Obviously it is your call but the license says to include itself in both source (the tarball you refer to as having the license) and binary distributions (I think this would include the wheels I referred to).  I'm pretty sure I would be breaking the license if I were to distribute the wheels as they are on PyPi right now.  'You', being the 'developers' are presumably not bound in the same way though.

Anyways, there were a few libraries like this so I'm just pulling the license files direct from GitHub to include in my installer.

**Comment by mgedmin** [comment]
FWIW https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/#configuration shows how to include a licence file in binary wheels.  AFAIU.  IANAL.
