### ISSUE TITLE
warning: "METH_KEYWORDS" redefined

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/zope.interface#71]
Noticed this scrolling by when I ran `python3.6 setup.py test` in zope.configuration:
```
src/zope/interface/_zope_interface_coptimizations.c:34:0: warning: "METH_KEYWORDS" redefined
 #define METH_KEYWORDS 0x0003
 
In file included from /home/mg/opt/python36/include/python3.6m/Python.h:91:0,
                 from src/zope/interface/_zope_interface_coptimizations.c:15:
/home/mg/opt/python36/include/python3.6m/methodobject.h:70:0: note: this is the location of the previous definition
 #define METH_KEYWORDS 0x0002
```

I don't know how serious this is.

Issue #60 is probably relevant.

**Comment by jamadden** [comment]
The [Python bug](http://bugs.python.org/issue15657) that @tseaver cited is still open in 3.6 and master, so some sort of fix is still needed. However, it's been open since2012 and, although there was a patch to change the value of `METH_KEYWORDS`, what actually got *merged* was a change to the documentation.

CPython itself never uses `METH_KEYWORDS` by itself, as far as I can see. It's always combined with `METH_VARARGS`. zope.interface, on the other hand, was using `METH_KEYWORDS` by itself; the documentation that was removed implied that this was acceptable, but the implementation didn't allow this. The proposed fix in CPython changed `METH_KEYWORDS` to be `0x2 | METH_VARARGS`, which is the patch that was applied to zope.interface. 

However, that results in the above warning.

So perhaps the better fix for zope.interface would be to change uses of the bare `METH_KEYWORDS` to `METH_KEYWORDS | METH_VARARGS` and remove the redefinition. As far as I can see, this is correct for Python 2.7 and onward.
