### ISSUE TITLE
'unsubscribe' / 'unregister' leak persistent references

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/zope.interface#9]
In https://bugs.launchpad.net/zope.interface/+bug/330000, @ctheune  reports:

> See zope.interface.adapter.BaseAdapterRegistry. The methods `unregister` and `unsubscribe` leave the attributes `_adapters` and `_subscribers` with an interface reference in their dictionary key although the value indicates an empty value and thus the key could be removed.
> 
> For persistent registries this causes the database to reference interfaces even after all registrations for those interfaces have been removed.

**Comment by jamadden** [comment]
I believe this was fixed in https://github.com/zopefoundation/zope.interface/commit/4ec9654e65bd39af169547ba1b33564c8d8d0bc3, part of 3.5.2. That was committed on 2009-06-30, while the original bug was opened on 2009-02-16.
