### ISSUE TITLE
Change in PR 92 breaks compatibility with Python 2.6.6

### ISSUE THREAD

**Issue by joshuaboniface** [zopefoundation/zope.interface#96]
https://github.com/zopefoundation/zope.interface/pull/92/files#diff-e92fa4ba4488a300b04dd1a578a2c7beR166

It appears that this change specifically causes a regression with Python 2.6.6 (in CentOS 6) when using Zope with the Certbot utility:

```
  File "/data/letsencrypt/virtualenv/lib/python2.6/site-packages/certbot/main.py", line 7, in <module>
    import zope.component
  File "/data/letsencrypt/virtualenv/lib/python2.6/site-packages/zope/component/__init__.py", line 28, in <module>
    from zope.component.globalregistry import getGlobalSiteManager
  File "/data/letsencrypt/virtualenv/lib/python2.6/site-packages/zope/component/globalregistry.py", line 18, in <module>
    from zope.interface.registry import Components
  File "/data/letsencrypt/virtualenv/lib/python2.6/site-packages/zope/interface/registry.py", line 167
    filtered_state = {k: v for k, v in reduction[2].items()
                             ^
SyntaxError: invalid syntax

$ python --version
Python 2.6.6
```

Perhaps there's another workaround instead but at the moment this breaks Certbot installed via PIP.

**Comment by jamadden** [comment]
Python 2.6 [hasn't been supported since 4.2.0](https://github.com/zopefoundation/zope.interface/blob/master/CHANGES.rst#420-2016-06-10).

**Comment by joshuaboniface** [comment]
Thanks for clarifying, I somehow missed that!

**Comment by joshuaboniface** [comment]
It actually looks like the changelog on pypi doesn't mention this:

https://pypi.python.org/pypi/zope.interface

```
4.4.0 (2017-04-21)
    Avoid a warning from the C compiler. (https://github.com/zopefoundation/zope.interface/issues/71)
    Add support for Python 3.6.
```

No mention of dropping Python 2.6 support.

**Comment by jamadden** [comment]
The change was in 4.*2*.0, not 4.4.0. 4.2.0 was released about a year ago, you may have to scroll to see [its notes](https://pypi.python.org/pypi/zope.interface#id8).

**Comment by joshuaboniface** [comment]
Yes, I noticed that after posting that >.< Didn't go down far enough and thought a 4 was a 3. Thanks for the quick responses!
