### ISSUE TITLE
Possible packaging issue

### ISSUE THREAD

**Issue by vog** [zopefoundation/zope.interface#97]
It is currently impossible to install both `zope.interface` and `zope.deprecation` with `pip install --target`. This is probably a bug in `setuptools`, but maybe it is also a packaging issue with `zope.interface` and `zope.deprecation`?

For details, see: https://github.com/pypa/setuptools/issues/1071

**Comment by frenzymadness** [comment]
There is one new change in namespace package `__init__.py`file so I think is worth to try to reproduce your issue with the latest master.

**Comment by tseaver** [comment]
I don't see how this can be an issue with `zope.interface`.  Please reopen / follow-up if you can suggest a change to our packaging which would prevent setuptools / pip from borking the installation.

**Comment by icemac** [comment]
@frenzymadness wrote:
> There is one new change in namespace package `__init__.py`file so I think is worth to try to reproduce your issue with the latest master.

@vog This change was released in version 4.5.0 of `zope.interface`.

**Comment by vog** [comment]
Thanks!
