### ISSUE TITLE
Interface definitions with Python 3.5+ type hints raise InvalidInterface

### ISSUE THREAD

**Issue by avanov** [zopefoundation/zope.interface#98]
Hi!

The following definition

```python

class ICriterion(Interface):
    name: str = Attribute('name')
```

raises  an exception:

```
zope.interface.exceptions.InvalidInterface: Concrete attribute, __annotations__
```

Seems like it could be fixed by playing around https://github.com/zopefoundation/zope.interface/blob/50a9193fea1e5873c59bf0add2e1ddca80c1bcf4/src/zope/interface/interface.py#L355 , but before that I'd like to clarify the position of `zope.interface` regarding `PEP484` and `PEP544` - are they mutually exclusive or could complement each other?

**Comment by tseaver** [comment]
- I think dropping `__annotatins__` (like `__locals__` and `__qualname__`) would be fine.
- PEP484 is kind of orthagonal to interfaces:  adopting it in a codebase which uses interfaces should be fine (but we won't do them, at least the inline version, while we support Python < 3.5).
- I don't know how interfaces fit with PEP544, except that they fall into its ["non-goals"](https://www.python.org/dev/peps/pep-0544/#non-goals). Personally, after nearly twenty years of using interfaces, I find ABCs utterly pointless.

**Comment by avanov** [comment]
@tseaver thanks! I'll prepare a PR for `__annotations__`.

**Comment by avanov** [comment]
Closing this.
